// WHAT ANOTHER PACKAGE'S DESIGNER IS TOLD ABOUT THIS APP'S SCREENS.
//
// @xeplr/ui-workflow's Screen step asks its host which screens exist and what
// each one hands back. This is @xeplr/factory's answer, and it lives here
// rather than in an application because a copy in each app generated by the
// CLI could never be fixed once — a control type added here would never reach
// any of them.
import { describeScreen, screenStub, loadScreens, keyFromName, editScreenOf } from '../src/screenSource.js'

const results = []
const check = (name, cond) => { results.push([name, cond]); console.log((cond ? '  ok   ' : '  FAIL ') + name) }

// A form as the builder saves one: fields mixed in with the furniture.
const TASK = {
  id: 'task_edit',
  name: 'Task',
  nodes: [
    { id: 'heading', type: 'label', x: 0, y: 0 },
    { id: 'steps', type: 'stepper', x: 0, y: 0.05 },
    { id: 'title', type: 'text', x: 0, y: 0.1 },
    { id: 'blocked', type: 'checkbox', x: 0, y: 0.3 },
    { id: 'dueDate', type: 'date', x: 0, y: 0.2 }
  ]
}

console.log('\na screen says what it holds')
{
  const d = describeScreen(TASK)
  check('it is known by its key', d.key === 'task_edit')
  check('and shown by its name', d.name === 'Task')

  // The whole reason this is not a list comprehension in an app: which nodes
  // hold a value is THIS package's question, and it answers it in one place.
  check('only the nodes that hold a value are fields',
    d.fields.map((f) => f.name).sort().join() === 'blocked,dueDate,title')
  check('a label is not a field', !d.fields.some((f) => f.name === 'heading'))
  check('nor is a stepper', !d.fields.some((f) => f.name === 'steps'))
  check('each field carries its type', d.fields.find((f) => f.name === 'dueDate').type === 'date')

  // Reading order, not declaration order — what somebody filling it in sees.
  check('fields are in the order they are read',
    d.fields.map((f) => f.name).join() === 'title,dueDate,blocked')

  check('a document with no id describes nothing', describeScreen({ name: 'x' }) === null)
  check('and neither does nothing at all', describeScreen(null) === null)
}

console.log('\nbefore its document has been read')
{
  check('a listing row is enough for the menu', screenStub({ screenKey: 'task_edit', name: 'Task' }).key === 'task_edit')
  check('a row with no name is known by its key', screenStub({ screenKey: 'plain' }).name === 'plain')
  check('a row with no key at all is skipped', screenStub({ name: 'nameless' }) === null)
}

console.log('\nevery screen, with its fields')
{
  const api = {
    listScreens: async () => [{ screenKey: 'task_edit', name: 'Task' }, { screenKey: 'broken', name: 'Broken' }],
    loadScreen: async (key) => {
      if (key === 'broken') throw new Error('gone')
      return TASK
    }
  }

  const seen = []
  const full = await loadScreens(api, (stubs) => seen.push(stubs.map((s) => s.key).join()))

  // Two passes: the menu is usable while the documents are still loading.
  check('the names are handed over first', seen[0] === 'task_edit,broken')
  check('then every screen comes back', full.map((s) => s.key).join() === 'task_edit,broken')
  check('...the ones that loaded, with their fields', full[0].fields.length === 3)

  // A screen whose document will not load is still choosable, with its output
  // typed by hand — missing from the menu would be worse.
  check('one that would not load is still in the list', full[1].key === 'broken')
  check('...simply without fields', full[1].fields === undefined)
}

console.log('\nmaking a new form')
{
  check('a key is made from the name', keyFromName('Leave request') === 'leave_request')
  check('punctuation and doubles collapse', keyFromName('  Leave — request!! ') === 'leave_request')
  check('nothing is an empty key, not a crash', keyFromName(null) === '')

  // Read off the answer rather than spelled out: the naming is this package's
  // and an app guessing "<key>_edit" would break quietly the day it changes.
  check('the form half is read from what createEntity said',
    editScreenOf({ entity: 'crop', edit: 'crop_edit', list: 'crop_list' }, 'x') === 'crop_edit')
  check('...whether it answered with a row or a key',
    editScreenOf({ edit: { id: 'crop_edit' } }, 'x') === 'crop_edit')
  check('...and falls back rather than failing', editScreenOf({}, 'crop_edit') === 'crop_edit')
}

const failed = results.filter(([, ok]) => !ok)
console.log(`\n${results.length - failed.length}/${results.length} passed`)
process.exit(failed.length ? 1 : 0)
